# Generated by Django 4.1.7 on 2024-04-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='img',
            field=models.CharField(max_length=225, verbose_name='商品图片'),
        ),
    ]
