# Generated by Django 4.1.7 on 2024-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_shoppingcart_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='latlon',
            field=models.CharField(default=1, max_length=52, verbose_name='商家经纬度'),
            preserve_default=False,
        ),
    ]
